import { Riddle } from '@/types';

export const RIDDLE_BANK: Record<string, Riddle[]> = {
  easy: [
    { id: 'e1', question: 'If you have 3 apples and take away 2, how many apples do you have?', answer: '2', answerVariants: ['2','two'], hint1: 'Think carefully — who is "you" in this problem?', hint2: 'You took 2 apples away, so you have those 2.', explanation: 'You took 2 apples, so you personally have 2 apples with you.', difficulty: 'easy', category: 'Logic' },
    { id: 'e2', question: 'A dozen eggs cost $2. How much do 3 eggs cost?', answer: '0.5', answerVariants: ['0.5','50 cents','$0.50','1/2','.5'], hint1: 'Find the cost of one egg first.', hint2: 'One egg = $2 ÷ 12 = $0.167. Now multiply by 3.', explanation: '$2 ÷ 12 × 3 = $0.50', difficulty: 'easy', category: 'Arithmetic' },
    { id: 'e3', question: 'What is 15% of 80?', answer: '12', answerVariants: ['12','twelve'], hint1: '10% of 80 is 8.', hint2: '15% = 10% + 5%. Add 8 + 4.', explanation: '0.15 × 80 = 12', difficulty: 'easy', category: 'Percentages' },
    { id: 'e4', question: 'A train travels at 60 km/h. How far does it travel in 90 minutes?', answer: '90', answerVariants: ['90','90 km','90km'], hint1: '90 minutes = 1.5 hours.', hint2: '60 × 1.5 = ?', explanation: '60 km/h × 1.5 h = 90 km', difficulty: 'easy', category: 'Speed & Distance' },
    { id: 'e5', question: 'What number comes next? 2, 4, 8, 16, __', answer: '32', answerVariants: ['32','thirty-two'], hint1: 'Each number is doubled.', hint2: '16 × 2 = ?', explanation: 'The pattern multiplies by 2. 16 × 2 = 32.', difficulty: 'easy', category: 'Patterns' },
    { id: 'e6', question: 'A rectangle is 8 cm long and 5 cm wide. What is its area?', answer: '40', answerVariants: ['40','40 cm2','40cm²','40 square cm'], hint1: 'Area = length × width.', hint2: '8 × 5 = ?', explanation: 'Area = 8 × 5 = 40 cm²', difficulty: 'easy', category: 'Geometry' },
    { id: 'e7', question: '5 workers build a wall in 10 days. How many days for 1 worker alone?', answer: '50', answerVariants: ['50','fifty'], hint1: 'More workers = fewer days.', hint2: '1 worker needs 5× as many days.', explanation: '5 × 10 = 50 days', difficulty: 'easy', category: 'Work & Rates' },
    { id: 'e8', question: 'What is 25% of 200?', answer: '50', answerVariants: ['50','fifty'], hint1: '25% is one quarter.', hint2: '200 ÷ 4 = ?', explanation: '200 × 0.25 = 50', difficulty: 'easy', category: 'Percentages' },
    { id: 'e9', question: 'A shirt costs $40 and is 20% off. What is the sale price?', answer: '32', answerVariants: ['32','$32','32 dollars'], hint1: 'Find 20% of $40.', hint2: '20% of 40 = 8. Sale price = 40 − 8.', explanation: '$40 − $8 = $32', difficulty: 'easy', category: 'Discounts' },
    { id: 'e10', question: 'What comes next? 1, 1, 2, 3, 5, 8, __', answer: '13', answerVariants: ['13','thirteen'], hint1: 'Each term = sum of previous two.', hint2: '5 + 8 = ?', explanation: 'Fibonacci: 5 + 8 = 13', difficulty: 'easy', category: 'Patterns' },
    { id: 'e11', question: 'What is the perimeter of a square with side 7 cm?', answer: '28', answerVariants: ['28','28 cm'], hint1: 'A square has 4 equal sides.', hint2: '4 × 7 = ?', explanation: '4 × 7 = 28 cm', difficulty: 'easy', category: 'Geometry' },
    { id: 'e12', question: 'You flip a fair coin twice. What is the probability of getting 2 heads?', answer: '0.25', answerVariants: ['0.25','1/4','25%'], hint1: 'P(heads) = 1/2 each flip.', hint2: '1/2 × 1/2 = ?', explanation: '(1/2)² = 1/4 = 0.25', difficulty: 'easy', category: 'Probability' },
    { id: 'e13', question: 'A car uses 6 litres per 100 km. How much fuel for 250 km?', answer: '15', answerVariants: ['15','15 litres','15L'], hint1: 'Find litres per km first.', hint2: '6/100 × 250 = ?', explanation: '6 × 2.5 = 15 litres', difficulty: 'easy', category: 'Rates' },
    { id: 'e14', question: 'What is the square root of 144?', answer: '12', answerVariants: ['12','twelve'], hint1: 'Think: what number times itself = 144?', hint2: '12 × 12 = 144', explanation: '√144 = 12', difficulty: 'easy', category: 'Arithmetic' },
    { id: 'e15', question: 'A shop sells 3 pens for $1.50. How much for 8 pens?', answer: '4', answerVariants: ['4','$4','4 dollars'], hint1: 'Find the cost of 1 pen.', hint2: '1 pen = $0.50', explanation: '8 × $0.50 = $4', difficulty: 'easy', category: 'Rates' },
    { id: 'e16', question: 'What is 3/4 as a decimal?', answer: '0.75', answerVariants: ['0.75','75%','.75'], hint1: 'Divide 3 by 4.', hint2: '3 ÷ 4 = ?', explanation: '3 ÷ 4 = 0.75', difficulty: 'easy', category: 'Fractions' },
    { id: 'e17', question: 'What is the sum of the first 10 natural numbers?', answer: '55', answerVariants: ['55','fifty-five'], hint1: 'Formula: n(n+1)/2.', hint2: '10 × 11 / 2 = ?', explanation: '10 × 11 / 2 = 55', difficulty: 'easy', category: 'Arithmetic' },
    { id: 'e18', question: 'A triangle has angles 90° and 45°. What is the third angle?', answer: '45', answerVariants: ['45','45°','forty-five'], hint1: 'Angles in a triangle sum to 180°.', hint2: '180 − 90 − 45 = ?', explanation: '180 − 90 − 45 = 45°', difficulty: 'easy', category: 'Geometry' },
    { id: 'e19', question: 'What is 2³ × 2²?', answer: '32', answerVariants: ['32','thirty-two'], hint1: 'Add exponents when multiplying same base.', hint2: '2^(3+2) = 2^5 = ?', explanation: '2^5 = 32', difficulty: 'easy', category: 'Exponents' },
    { id: 'e20', question: 'If a pizza is cut into 8 equal slices and you eat 3, what fraction is left?', answer: '0.625', answerVariants: ['0.625','5/8','62.5%'], hint1: 'How many slices remain?', hint2: '5 out of 8 remain.', explanation: '5/8 = 0.625', difficulty: 'easy', category: 'Fractions' },
  ],
  medium: [
    { id: 'm1', question: 'A clock shows 3:15. What is the exact angle between the hands?', answer: '7.5', answerVariants: ['7.5','7.5 degrees','7.5°'], hint1: 'At exactly 3:00, the angle is 90°.', hint2: 'The hour hand moves 0.5° per minute. In 15 minutes it moves 7.5°.', explanation: 'Hour hand at 97.5°, minute hand at 90°. Difference = 7.5°', difficulty: 'medium', category: 'Angles' },
    { id: 'm2', question: 'Two pipes fill a tank in 6 hrs and 12 hrs respectively. How long together?', answer: '4', answerVariants: ['4','4 hours','four'], hint1: 'Add their rates: 1/6 + 1/12.', hint2: '1/6 + 1/12 = 2/12 + 1/12 = 3/12 = 1/4', explanation: 'Combined rate = 1/4 tank/hr. Time = 4 hours.', difficulty: 'medium', category: 'Work & Rates' },
    { id: 'm3', question: 'Solve for x: 3x + 7 = 22', answer: '5', answerVariants: ['5','five'], hint1: 'Subtract 7 from both sides.', hint2: '3x = 15, then divide by 3.', explanation: '3x = 15 → x = 5', difficulty: 'medium', category: 'Algebra' },
    { id: 'm4', question: 'What is the LCM of 12 and 18?', answer: '36', answerVariants: ['36','thirty-six'], hint1: 'Find the prime factorizations.', hint2: '12 = 2²×3, 18 = 2×3². LCM = 2²×3².', explanation: '2² × 3² = 4 × 9 = 36', difficulty: 'medium', category: 'Number Theory' },
    { id: 'm5', question: 'A man walks 3 km north and 4 km east. How far is he from the start?', answer: '5', answerVariants: ['5','5 km','five'], hint1: 'This is a right triangle.', hint2: '√(3² + 4²) = ?', explanation: '√(9 + 16) = √25 = 5 km', difficulty: 'medium', category: 'Geometry' },
    { id: 'm6', question: 'The average of 5 numbers is 20. Four are 18, 22, 16, 24. Find the fifth.', answer: '20', answerVariants: ['20','twenty'], hint1: 'Total sum = average × count = 100.', hint2: '100 − (18+22+16+24) = ?', explanation: '100 − 80 = 20', difficulty: 'medium', category: 'Statistics' },
    { id: 'm7', question: 'A train 200 m long crosses a 300 m bridge at 25 m/s. Time taken?', answer: '20', answerVariants: ['20','20 seconds','20s'], hint1: 'Total distance = train length + bridge length.', hint2: '500 ÷ 25 = ?', explanation: '(200 + 300) ÷ 25 = 20 seconds', difficulty: 'medium', category: 'Speed & Distance' },
    { id: 'm8', question: 'What is 7! (7 factorial)?', answer: '5040', answerVariants: ['5040'], hint1: '7! = 7 × 6 × 5 × 4 × 3 × 2 × 1.', hint2: '7 × 720 = ?', explanation: '7! = 5040', difficulty: 'medium', category: 'Combinatorics' },
    { id: 'm9', question: 'P(A) = 0.3, P(B) = 0.5. If A and B are independent, find P(A and B).', answer: '0.15', answerVariants: ['0.15','15%','.15'], hint1: 'For independent events, multiply probabilities.', hint2: '0.3 × 0.5 = ?', explanation: '0.3 × 0.5 = 0.15', difficulty: 'medium', category: 'Probability' },
    { id: 'm10', question: 'Find the slope between points (2, 3) and (6, 11).', answer: '2', answerVariants: ['2','two'], hint1: 'Slope = (y₂ − y₁) / (x₂ − x₁).', hint2: '(11 − 3) / (6 − 2) = ?', explanation: '8 / 4 = 2', difficulty: 'medium', category: 'Coordinate Geometry' },
    { id: 'm11', question: 'How many ways can 4 people be arranged in a row?', answer: '24', answerVariants: ['24','twenty-four'], hint1: 'First position: 4 choices, second: 3...', hint2: '4! = 4 × 3 × 2 × 1', explanation: '4! = 24', difficulty: 'medium', category: 'Combinatorics' },
    { id: 'm12', question: 'Simple interest on $5000 at 8% per year for 3 years?', answer: '1200', answerVariants: ['1200','$1200'], hint1: 'SI = P × R × T / 100.', hint2: '5000 × 8 × 3 / 100 = ?', explanation: '5000 × 0.08 × 3 = $1200', difficulty: 'medium', category: 'Finance' },
    { id: 'm13', question: 'What is the sum of interior angles of a hexagon?', answer: '720', answerVariants: ['720','720°','720 degrees'], hint1: 'Formula: (n − 2) × 180°.', hint2: '(6 − 2) × 180 = ?', explanation: '4 × 180 = 720°', difficulty: 'medium', category: 'Geometry' },
    { id: 'm14', question: 'Solve: 2x² − 8 = 0. Give the positive root.', answer: '2', answerVariants: ['2','two'], hint1: 'Isolate x².', hint2: 'x² = 4, so x = ±2.', explanation: 'x² = 4 → x = 2 (positive root)', difficulty: 'medium', category: 'Algebra' },
    { id: 'm15', question: 'What is the GCD of 48 and 36?', answer: '12', answerVariants: ['12','twelve'], hint1: 'List factors of each number.', hint2: 'Common factors: 1, 2, 3, 4, 6, 12', explanation: 'GCD(48, 36) = 12', difficulty: 'medium', category: 'Number Theory' },
    { id: 'm16', question: 'If log₂(x) = 5, what is x?', answer: '32', answerVariants: ['32','thirty-two'], hint1: 'log₂(x) = 5 means 2^5 = x.', hint2: '2^5 = ?', explanation: 'x = 2^5 = 32', difficulty: 'medium', category: 'Logarithms' },
    { id: 'm17', question: 'A square is inscribed in a circle of radius 5. What is the square\'s area?', answer: '50', answerVariants: ['50','50 sq units'], hint1: 'Diagonal of square = diameter = 10.', hint2: 'Area = d² / 2', explanation: '10² / 2 = 100 / 2 = 50 sq units', difficulty: 'medium', category: 'Geometry' },
    { id: 'm18', question: 'In how many ways can 3 people be chosen from 7?', answer: '35', answerVariants: ['35','thirty-five'], hint1: 'Use combination: C(n, r) = n! / (r!(n-r)!)', hint2: 'C(7, 3) = 7! / (3! × 4!)', explanation: '(7 × 6 × 5) / (3 × 2 × 1) = 35', difficulty: 'medium', category: 'Combinatorics' },
    { id: 'm19', question: 'A bag has 5 red and 3 blue balls. P(both red) for 2 draws without replacement?', answer: '0.357', answerVariants: ['0.357','5/14','.357'], hint1: 'First draw: 5/8. After that: 4/7.', hint2: '(5/8) × (4/7) = 20/56', explanation: '20/56 = 5/14 ≈ 0.357', difficulty: 'medium', category: 'Probability' },
    { id: 'm20', question: 'A ball is dropped from 100 m. Each bounce reaches half the previous height. Total distance after 3 bounces?', answer: '275', answerVariants: ['275','275 m'], hint1: 'Track each drop and bounce separately.', hint2: '100 + 50+50 + 25+25 + 12.5+12.5', explanation: '100 + 100 + 50 + 25 = 275 m', difficulty: 'medium', category: 'Series' },
  ],
  hard: [
    { id: 'h1', question: 'How many trailing zeros does 100! have?', answer: '24', answerVariants: ['24','twenty-four'], hint1: 'Count factors of 5 in 100!.', hint2: '⌊100/5⌋ + ⌊100/25⌋ = 20 + 4.', explanation: '20 + 4 = 24 trailing zeros', difficulty: 'hard', category: 'Number Theory' },
    { id: 'h2', question: 'If x + 1/x = 3, find x² + 1/x².', answer: '7', answerVariants: ['7','seven'], hint1: 'Square both sides of x + 1/x = 3.', hint2: '9 = x² + 2 + 1/x², so x² + 1/x² = ?', explanation: '(x + 1/x)² = 9 → x² + 2 + 1/x² = 9 → x² + 1/x² = 7', difficulty: 'hard', category: 'Algebra' },
    { id: 'h3', question: 'A geometric series has first term 2, ratio 3. Sum of first 5 terms?', answer: '242', answerVariants: ['242'], hint1: 'S = a(rⁿ − 1) / (r − 1).', hint2: '2(3⁵ − 1) / (3 − 1) = 2 × 242 / 2.', explanation: '2(243 − 1) / 2 = 242', difficulty: 'hard', category: 'Series' },
    { id: 'h4', question: 'What is the remainder when 2^100 is divided by 3?', answer: '1', answerVariants: ['1','one'], hint1: '2^1 mod 3 = 2, 2^2 mod 3 = 1. Pattern repeats.', hint2: '100 is even, so pattern gives remainder 1.', explanation: '2^even mod 3 = 1', difficulty: 'hard', category: 'Number Theory' },
    { id: 'h5', question: 'Solve: x² − 5x + 6 = 0. What is the larger root?', answer: '3', answerVariants: ['3','three'], hint1: 'Factor into (x − ?)(x − ?).', hint2: '(x − 2)(x − 3) = 0', explanation: 'x = 2 or x = 3. Larger root = 3.', difficulty: 'hard', category: 'Algebra' },
    { id: 'h6', question: 'A cube has surface area 96 cm². What is its volume?', answer: '64', answerVariants: ['64','64 cm3','64cm³'], hint1: '6 × side² = 96, so side² = 16.', hint2: 'side = 4, volume = 4³.', explanation: 'side = 4, V = 4³ = 64 cm³', difficulty: 'hard', category: 'Geometry' },
    { id: 'h7', question: 'How many 3-digit numbers are divisible by 12?', answer: '75', answerVariants: ['75','seventy-five'], hint1: 'Find 3-digit multiples of 12.', hint2: '⌊999/12⌋ − ⌊99/12⌋ = 83 − 8.', explanation: '83 − 8 = 75', difficulty: 'hard', category: 'Number Theory' },
    { id: 'h8', question: 'If sinθ = 3/5 (first quadrant), find cosθ.', answer: '0.8', answerVariants: ['0.8','4/5','.8'], hint1: 'Use sin²θ + cos²θ = 1.', hint2: 'cos²θ = 1 − 9/25 = 16/25.', explanation: 'cosθ = 4/5 = 0.8', difficulty: 'hard', category: 'Trigonometry' },
    { id: 'h9', question: 'What is the sum of the first 10 perfect squares?', answer: '385', answerVariants: ['385'], hint1: 'Formula: n(n+1)(2n+1)/6.', hint2: '10 × 11 × 21 / 6 = ?', explanation: '2310 / 6 = 385', difficulty: 'hard', category: 'Series' },
    { id: 'h10', question: 'What is the derivative of x³ − 3x + 2 at x = 2?', answer: '9', answerVariants: ['9','nine'], hint1: 'Differentiate: f′(x) = 3x² − 3.', hint2: 'f′(2) = 3(4) − 3 = ?', explanation: '12 − 3 = 9', difficulty: 'hard', category: 'Calculus' },
    { id: 'h11', question: 'How many prime numbers exist between 1 and 50?', answer: '15', answerVariants: ['15','fifteen'], hint1: 'Primes start at 2, 3, 5, 7…', hint2: 'Last prime ≤ 50 is 47. Count carefully.', explanation: '2,3,5,7,11,13,17,19,23,29,31,37,41,43,47 = 15 primes', difficulty: 'hard', category: 'Number Theory' },
    { id: 'h12', question: 'Compound interest on $2000 at 10% p.a. for 2 years (compounded annually)?', answer: '420', answerVariants: ['420','$420'], hint1: 'CI = P(1 + r)ⁿ − P.', hint2: '2000 × 1.21 − 2000 = ?', explanation: '2000 × 1.21 − 2000 = $420', difficulty: 'hard', category: 'Finance' },
    { id: 'h13', question: 'Sum of the infinite series: 1/2 + 1/4 + 1/8 + ...', answer: '1', answerVariants: ['1','one'], hint1: 'Infinite geometric series: S = a / (1 − r).', hint2: '(1/2) / (1 − 1/2) = ?', explanation: '(0.5) / (0.5) = 1', difficulty: 'hard', category: 'Series' },
    { id: 'h14', question: 'A committee of 3 is chosen from 8 people. How many ways?', answer: '56', answerVariants: ['56','fifty-six'], hint1: 'C(n, r) = n! / (r!(n−r)!)', hint2: 'C(8, 3) = 8 × 7 × 6 / 6.', explanation: '336 / 6 = 56', difficulty: 'hard', category: 'Combinatorics' },
    { id: 'h15', question: 'If f(x) = 2x + 3 and g(x) = x², what is f(g(3))?', answer: '21', answerVariants: ['21','twenty-one'], hint1: 'Compute g(3) first.', hint2: 'g(3) = 9, then f(9) = ?', explanation: 'g(3) = 9, f(9) = 18 + 3 = 21', difficulty: 'hard', category: 'Functions' },
    { id: 'h16', question: 'Solve: 4^x = 64.', answer: '3', answerVariants: ['3','three'], hint1: 'Express 64 as a power of 4.', hint2: '4³ = 64', explanation: '4^x = 4³ → x = 3', difficulty: 'hard', category: 'Exponents' },
    { id: 'h17', question: 'A cylinder has radius 3 and height 10. Volume? (π ≈ 3.14)', answer: '282.6', answerVariants: ['282.6','282.74'], hint1: 'V = πr²h.', hint2: '3.14 × 9 × 10 = ?', explanation: '3.14 × 9 × 10 = 282.6', difficulty: 'hard', category: 'Geometry' },
    { id: 'h18', question: 'Area of an equilateral triangle with side 6 (in surd form)?', answer: '9√3', answerVariants: ['9√3','9*√3','15.59','15.6','9 root 3'], hint1: 'Area = (√3/4) × a².', hint2: '(√3/4) × 36 = 9√3', explanation: 'Area = 9√3 ≈ 15.59 sq units', difficulty: 'hard', category: 'Geometry' },
    { id: 'h19', question: 'Find x if log₁₀(x) + log₁₀(x−3) = 1.', answer: '5', answerVariants: ['5','five'], hint1: 'Combine logs: log₁₀(x(x−3)) = 1.', hint2: 'x(x−3) = 10. Solve the quadratic.', explanation: 'x²−3x−10=0 → (x−5)(x+2)=0 → x=5', difficulty: 'hard', category: 'Logarithms' },
    { id: 'h20', question: 'Evaluate: ∫(0 to 2) x² dx', answer: '2.667', answerVariants: ['2.667','8/3','2.67','2⅔'], hint1: 'Antiderivative of x² is x³/3.', hint2: '[x³/3] from 0 to 2 = 8/3 − 0.', explanation: '8/3 ≈ 2.667', difficulty: 'hard', category: 'Calculus' },
  ],
};

export function getRiddleByDateAndDifficulty(date: string, difficulty: string): Riddle {
  const bank = RIDDLE_BANK[difficulty] ?? RIDDLE_BANK.easy;
  const parts = date.split('-');
  const seed = parseInt(parts[0]) * 10000 + parseInt(parts[1]) * 100 + parseInt(parts[2]);
  const index = Math.abs(seed) % bank.length;
  return bank[index];
}
